export const columnsData: string[] = [
  "Action",
  "Building",
  "Floor",
  "Unit",
  "Asset Name",
  "OEM Name",
  "Asset Number",
  "Equipment Id",
  "Serial Number",
  "Model Number",
  "Group",
  "Sub Group",
  "Critical",
  "Capacity",
  "Purchase Date",
  "Purchase Cost",
  "Status",
  "Created On",
  "Updated On",
  "W Start",
  "W Expiry",
  "Installation Date",
  "Meter Configured",
  "Supplier",
];
